# Generated by Django 6.0.5 on 2026-05-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Mecanico', 'Mecánico'), ('Admin', 'Administrador'), ('Mostrador', 'Empleado de Mostrador')], default='Empleado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cilindrada', models.IntegerField()),
                ('dni_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: S001', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mecanico', models.ForeignKey(limit_choices_to={'rol': 'Mecanico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.empleado')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.motocicleta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.servicio')),
            ],
        ),
    ]
